import type { LLMSource, Ticket, TicketStatus } from '../types'
import {
  createCompanionTicket,
  deleteCompanionTicket,
  listCompanionTickets,
  updateCompanionTicket,
  decideGmailCandidate,
  getGmailCheck,
  getGmailSourceStatus,
  listGmailCandidates,
  startGmailCheck,
  associateGmailCandidate,
  getReconciliationRun,
  listReconciliationRuns,
  listReconciliationSources,
  getOnboardingSnapshot,
  startOnboardingRefresh,
  retryReconciliation,
  startReconciliation,
  previewLegacyMigration,
  commitLegacyMigration,
  connectGmail,
  discoverRoutingDestinations,
  getPiModelCatalog,
  listRoutingDispatchReceipts,
  cancelRoutingDispatch,
  retryRoutingDispatch,
  commitOperationalRoutingMigration,
  exportOperationalRoutingPolicyV1,
  getOperationalRoutingPolicy,
  previewOperationalRoutingMigration,
  refreshPiModelCatalog,
  updateOperationalRoutingPolicy,
  validateOperationalRoutingProfile,
  getUsageCapability,
  startUsageRefresh,
  getUsageRefresh,
  cancelUsageRefresh,
  getUsageSummary,
  getUsageRecords,
  getUsageCoverage,
  listUsageMappings,
  saveUsageMapping,
  removeUsageMapping,
  getUsageRouteObservations,
  downloadUsageExport,
  clearUsageHistory,
  clearUsageMappings,
  getDataExportPreview,
  downloadDataBundle,
  previewDataImport,
  commitDataImport,
  listRoutingConnections,
  discoverRoutingConnections,
  refreshRoutingConnection,
  getRoutingConnectionCatalog,
  setRoutingConnectionEnabled,
  getOperationalRoutingPolicyV3,
  updateOperationalRoutingPolicyV3,
  validateOperationalRoutingProfileV3,
  listProjectFolderSummaries,
  updateProjectFolderSummary,
  removeProjectFolderSummary,
  startOpenRouterConnection,
  type CompanionSession,
  queryCompletedWork,
  exportCompletedWork,
  listAgentActivityIntegrations,
  listAgentActivityAssignments,
  updateAgentActivityAssignment,
  manageAgentActivity,
  listAgentActivityProjectReviews,
  resolveAgentActivityProjectReview,
} from './companion-client'
import type { OperationalRepository } from './operational-repository'

export function createCompanionRepository(session: CompanionSession): OperationalRepository {
  return {
    listTickets: () => listCompanionTickets(session),
    createTicket: async (title: string, description: string, source: LLMSource) => {
      const now = new Date().toISOString()
      return createCompanionTicket(session, {
        id: crypto.randomUUID(),
        title: title.trim(),
        description: description.trim(),
        source,
        status: 'todo',
        workNotes: [],
        artifacts: [],
        decisionLog: [],
        createdAt: now,
        updatedAt: now,
        completedAt: null,
        origin: 'browser-ui',
      })
    },
    updateTicketStatus: (ticket: Ticket, status: TicketStatus) => updateCompanionTicket(session, { ...ticket, status }),
    addWorkNote: (ticket: Ticket, text: string) => updateCompanionTicket(session, {
      ...ticket,
      workNotes: [...ticket.workNotes, { id: crypto.randomUUID(), text: text.trim(), createdAt: new Date().toISOString() }],
    }),
    deleteTicket: (ticketId: string) => deleteCompanionTicket(session, ticketId),
    queryCompletedWork: (query) => queryCompletedWork(session, query),
    downloadCompletedWork: async (query, format) => {
      const blob = await exportCompletedWork(session, query, format)
      const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `findmnemo-completed-work.${format}`; anchor.click(); URL.revokeObjectURL(url)
    },
    listEmailCandidates: () => listGmailCandidates(session),
    startGmailCheck: () => startGmailCheck(session),
    getGmailCheck: (runId: string) => getGmailCheck(session, runId),
    getGmailSourceStatus: () => getGmailSourceStatus(session),
    connectGmail: () => connectGmail(session),
    decideEmailCandidate: (candidate, action) => decideGmailCandidate(session, candidate, action),
    associateEmailCandidate: (candidate, input, idempotencyKey) => associateGmailCandidate(session, candidate, input, idempotencyKey),
    listReconciliationSources: () => listReconciliationSources(session),
    getOnboardingSnapshot: () => getOnboardingSnapshot(session),
    startOnboardingRefresh: (sourceIds) => startOnboardingRefresh(session, sourceIds),
    listAgentActivityIntegrations: () => listAgentActivityIntegrations(session),
    listAgentActivityAssignments: (query) => listAgentActivityAssignments(session, query),
    updateAgentActivityAssignment: (assignmentId, input) => updateAgentActivityAssignment(session, assignmentId, input),
    manageAgentActivity: (integrationId, action, confirmed) => manageAgentActivity(session, integrationId, action, confirmed),
    listAgentActivityProjectReviews: () => listAgentActivityProjectReviews(session),
    resolveAgentActivityProjectReview: (reviewId, projectId, confirmed) => resolveAgentActivityProjectReview(session, reviewId, projectId, confirmed),
    startReconciliation: (sourceIds) => startReconciliation(session, sourceIds),
    getReconciliationRun: (runId) => getReconciliationRun(session, runId),
    listReconciliationRuns: () => listReconciliationRuns(session),
    retryReconciliation: (runId, sourceIds) => retryReconciliation(session, runId, sourceIds),
    previewLegacyMigration: (records) => previewLegacyMigration(session, records),
    commitLegacyMigration: (records, idempotencyKey) => commitLegacyMigration(session, records, idempotencyKey),
    getRoutingPolicy: () => getOperationalRoutingPolicy(session),
    updateRoutingPolicy: (policy, expectedPolicyVersion) => updateOperationalRoutingPolicy(session, policy, expectedPolicyVersion),
    previewRoutingMigration: (preview) => previewOperationalRoutingMigration(session, preview),
    commitRoutingMigration: (preview, idempotencyKey) => commitOperationalRoutingMigration(session, preview, idempotencyKey),
    exportRoutingPolicyV1: () => exportOperationalRoutingPolicyV1(session),
    discoverRoutingDestinations: () => discoverRoutingDestinations(session),
    refreshPiModelCatalog: () => refreshPiModelCatalog(session),
    getPiModelCatalog: () => getPiModelCatalog(session),
    validateRoutingProfile: (profileId, expectedPolicyVersion) => validateOperationalRoutingProfile(session, profileId, expectedPolicyVersion),
    listRoutingDispatchReceipts: () => listRoutingDispatchReceipts(session),
    listRoutingConnections: () => listRoutingConnections(session),
    discoverRoutingConnections: () => discoverRoutingConnections(session),
    refreshRoutingConnection: (connectionId) => refreshRoutingConnection(session, connectionId),
    getRoutingConnectionCatalog: (connectionId) => getRoutingConnectionCatalog(session, connectionId),
    setRoutingConnectionEnabled: (connectionId, enabled) => setRoutingConnectionEnabled(session, connectionId, enabled),
    getRoutingPolicyV3: () => getOperationalRoutingPolicyV3(session),
    updateRoutingPolicyV3: (policy, expectedPolicyVersion) => updateOperationalRoutingPolicyV3(session, policy, expectedPolicyVersion),
    validateRoutingProfileV3: (profileId) => validateOperationalRoutingProfileV3(session, profileId),
    listProjectFolders: () => listProjectFolderSummaries(session),
    updateProjectFolder: (id, input) => updateProjectFolderSummary(session, id, input),
    removeProjectFolder: (id) => removeProjectFolderSummary(session, id),
    startOpenRouterConnection: () => startOpenRouterConnection(session),
    cancelRoutingDispatch: (receiptId) => cancelRoutingDispatch(session, receiptId),
    retryRoutingDispatch: (receiptId, idempotencyKey) => retryRoutingDispatch(session, receiptId, idempotencyKey),
    getUsageCapability: () => getUsageCapability(session),
    startUsageRefresh: (input) => startUsageRefresh(session, input),
    getUsageRefresh: (runId) => getUsageRefresh(session, runId),
    cancelUsageRefresh: (runId) => cancelUsageRefresh(session, runId),
    getUsageSummary: (filters) => getUsageSummary(session, filters),
    getUsageRecords: (filters, cursor) => getUsageRecords(session, filters, cursor),
    getUsageCoverage: () => getUsageCoverage(session),
    listUsageMappings: () => listUsageMappings(session),
    saveUsageMapping: (mapping) => saveUsageMapping(session, mapping),
    removeUsageMapping: (identityKey) => removeUsageMapping(session, identityKey),
    getUsageRouteObservations: (filters) => getUsageRouteObservations(session, filters),
    downloadUsageExport: (filters, format, includeAttribution) => downloadUsageExport(session, filters, format, includeAttribution),
    clearUsageHistory: () => clearUsageHistory(session),
    clearUsageMappings: () => clearUsageMappings(session),
    getDataExportPreview: () => getDataExportPreview(session),
    downloadDataBundle: (categoryIds) => downloadDataBundle(session, categoryIds),
    previewDataImport: (bundle) => previewDataImport(session, bundle),
    commitDataImport: (input) => commitDataImport(session, input),
  }
}
